5 feature tests
Zheka1988/qna pull request #3
Opened 2021-06-26 20:05 UTC by Zheka1988

2021-06-27 11:55 UTC, vkurennov requested changes

2021-06-27 11:55 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  -if current_user == answer.author
замени на взыов метода `author_of?`

2021-06-27 11:55 UTC, vkurennov commented on app/views/questions/index.html.slim
> +  -if current_user == question.author
замени на взыов метода `author_of?`

2021-06-27 11:55 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe "DELETE #destroy" do
вопросы тоже меожет удалять только автор - нужны тесты и проверка на автора в контроллере

2021-06-27 11:55 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +      expect(page).to have_content 'MyText', count: 1
как это проверяет, что ответ удален? может он и был один на странице и он же и остался? надо перед удалением проверить, что ответ на странцие есть (либо их кол-во другое), а потом то, что его нет

2021-06-27 11:55 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +      expect(page).to have_no_content 'MyText'
перед удалением надо проверить, что такой вопрос есть на странице

2021-06-28 02:40 UTC, Zheka1988 commented on spec/features/answer/delete_spec.rb
> +      expect(page).to have_content 'MyText', count: 1
Я поленился переименовать в факториях тело ответа. Они у меня одинаковы. 
```
factory :answer do
    **body { "MyText" }** ...
```
```
factory :question do
    title { "MyString" }
    **body { "MyText" }**
```
expect(page).to have_content 'MyText', count: 1 Поэтому только один, который принадлежит ответу. До этого было 2

2021-06-28 02:45 UTC, Zheka1988 commented on app/views/answers/_answer.html.slim
> +  -if current_user == answer.author
Здесь изначально у меня был вызов метода `author_of?` (в методе идет вызов author_id), но  он выдавал ошибку типа "authot_id не может вызваться у nil", почему то answer он принимал как в методе как nil. И я заменил на `current_user == answer.author`. Аналогичная история с вопросом.

2021-06-28 09:00 UTC, vkurennov approved these changes

2021-06-28 11:58 UTC, merged